
services:
  backend:
    build: ./backend
    ports:
      - "8000:10000"
    environment:
      - JWT_SECRET=supersecret_change_me
      - FRONTEND_ORIGINS=http://localhost:3000
    volumes:
      - ./backend/app/sql_runner.db:/app/sql_runner.db
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_BASE=http://host.docker.internal:8000/api
